### ISSUE TITLE
Frontend: Putting in a temporary avatar

### ISSUE THREAD

**Issue by edmcentee** [jathonderulo/SwEngGroup27#33]
Inserting an avatar in the right side of the screen. Some form of animation (not specific to the backend output) would be great but not compulsory. Try and keep the avatar as close to being as human like as possible (use online inspiration). Make sure to create a branch from the frontend, make a new .jsx file in the components folder, and a new.css file in the styles folder.

**Comment by wardr3** [comment]
This is done, but not animated yet. Refer to issue #45 for progress.
