### ISSUE TITLE
Backend: Allow the AI response to come out word by word 

### ISSUE THREAD

**Issue by edmcentee** [jathonderulo/SwEngGroup27#46]
Make the words in the response flow as opposed to all coming out at once. This will allow the avatar to act like it is speaking more naturally

**Comment by wardr3** [comment]
As of right now the Assistants API does not support streaming, but it is very close to becoming publicly supported. I will probably put this issue on the back burner for a short while in the hopes that streaming support goes live in the next week or so.

**Comment by wardr3** [comment]
## Backend implementation complete
- Now awaiting frontend adjustment to support the streamed response

**Comment by wardr3** [comment]
This is now fully implemented
